FROM 763104351884.dkr.ecr.us-east-2.amazonaws.com/pytorch-inference:2.0.1-gpu-py310-cu118-ubuntu20.04-sagemaker
# preinstall dependencies for faster build
RUN pip install --upgrade pip && \
    pip install --no-cache-dir -U taichi==1.6.0 matplotlib numpy pytorch_msssim dataclass-wizard pillow pyyaml pandas[parquet]==2.0.0 scipy argparse tensorboard
COPY . /opt/ml/code
WORKDIR /opt/ml/code
RUN pip install -r requirements.txt
RUN pip install -e .
